## Numpy Arrays

In [1]:
import numpy as np
np.version

<module 'numpy.version' from 'C:\\Users\\star\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [13]:
my_list = [[1,2,3]]  # single dimention array 
np.array(my_list)

array([[1, 2, 3]])

In [16]:
my_list.append([4,5,6])
my_list.append([7,8,9])

In [17]:
my_list

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_list)   # multi dimentional array

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(0,11,3)  # arrange(start, stop, step size) top is not included in the range

array([0, 3, 6, 9])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((5,3)) #if a tuple is passed as an argument then first no. gives the no. of rows while the second no. gives the no. of columns in the arra

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [3]:
import numpy as np
np.eye(5)  # create an identity matrix of order 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.random.rand(5) # 1D array of random values between 0 to 1

array([0.40472969, 0.45520769, 0.90673251, 0.296752  , 0.44922388])

In [6]:
np.random.rand(3,4)

array([[0.10247439, 0.21211629, 0.75428799, 0.99815679],
       [0.77655562, 0.57661766, 0.42044197, 0.51161864],
       [0.12458082, 0.87580351, 0.3603977 , 0.54352074]])

In [10]:
np.random.randn(6)  # gives no.s that are surround 0

array([-0.71792924,  0.0951592 ,  0.08279378, -3.01833967, -0.31702572,
        1.19264886])

In [12]:
np.random.randn(3,3)

array([[ 2.34439125,  1.42552335,  2.38163253],
       [ 0.21639638, -0.43692304, -0.04859309],
       [-1.86840496,  0.81189339, -0.88661691]])

In [13]:
np.random.randint(1,100)  # generates random output including 0 and excluding 100

37

In [14]:
np.random.randint(1,100,10)  # here 10 is the size or the no. of random outputs to be generated

array([24, 42, 71, 90, 90, 53, 34, 85, 98,  2])

In [28]:
arr = np.arange(0,25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr.reshape(5,5) # the order of new reshaped array should be equal to the elements present in the array otherwise error is thrown

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
rarr = np.random.randint(0,25,10)

In [42]:
rarr

array([23,  4, 11, 14, 24,  1, 18, 13, 17,  8])

In [43]:
rarr.reshape(2,5)

array([[23,  4, 11, 14, 24],
       [ 1, 18, 13, 17,  8]])

In [44]:
rarr.min()

1

In [45]:
rarr.max()

24

In [46]:
rarr.argmin()

5

In [47]:
rarr.argmax()

4

## Numpy Array Indexing

In [55]:
import numpy as np
ar = np.arange(1,11)

In [57]:
ar.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
ar.sum()

55

In [8]:
ar[0:5] # we can perform slicing on arrays

array([0, 1, 2, 3, 4])

In [10]:
ar[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
ar[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
ar[0:5] = 100      # broadcasting values at index 0 to 4

In [14]:
ar # broadcasting is possible in numpy arrays unlike normal python list

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
slice_ar = ar[0:5] 

In [18]:
slice_ar

array([100, 100, 100, 100, 100])

In [19]:
slice_ar[:] = 60

In [20]:
slice_ar

array([60, 60, 60, 60, 60])

In [22]:
ar

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

Thus the above five lines of code shows that data is not copied to another array i.e. slice_ar but its just a view of original data. Hence any changes in it (slice_ar) will reflect back in the main array i.e ar.

It also avoids memory issues with large arrays. As unnecessary copies are not generated. If we need any copy rather than reference we can explicitly mention through copy().

In [23]:
ar_copy = ar.copy()
ar_copy

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

In [24]:
ar

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

In [25]:
ar_copy[:] = 100
ar_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
ar

array([60, 60, 60, 60, 60,  5,  6,  7,  8,  9, 10])

This shows that the original array is unaffected when changes are carried in the copied array 

In [6]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[1][2]  # double bracket notation

30

In [30]:
arr_2d[1,2]   # single bracket notation

30

In [34]:
r = np.arange(1,11)

In [35]:
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
bol = r > 5

In [41]:
bol

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
r[bol] #by applying condional selection now only those values are returned which are true

array([ 6,  7,  8,  9, 10])

The above five lines can be carried out in one line as-

In [44]:
r[r>5]

array([ 6,  7,  8,  9, 10])

In [48]:
# grab elements less than 3
r[r<3]

array([1, 2])

In [5]:
ar_2d = np.arange(0,50).reshape(5,10)

In [6]:
ar_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
ar_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [8]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr_length = arr2d.shape[1] # here 1 is the dimension

In [10]:
arr_length

10

In [11]:
for i in range(arr_length) :
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

## Numpy Operations 

1. array with array___2. array with scalar___3. universal array functions

In [13]:
import numpy as np

In [14]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr + arr     # array with array operation

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [21]:
arr - 1     # array with scalar

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [24]:
arr / arr  # throws a warning rather than error and nan (no object back) is return in place of the not defined output

C:\Users\star\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
1 / arr    # inf is fr infinity

C:\Users\star\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [26]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [27]:
np.sqrt(arr)     # universal array functions

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [28]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [29]:
np.max(arr)

10

In [30]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [36]:
np.log(arr)

C:\Users\star\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [42]:
5 * np.ones((3,3))

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [45]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.random.rand(1)

array([0.06934484])

In [47]:
np.random.rand(10,10)

array([[0.24731519, 0.0368382 , 0.96171063, 0.00606479, 0.84291982,
        0.09882531, 0.1041633 , 0.01396934, 0.64388435, 0.64839176],
       [0.53567276, 0.82534495, 0.38853118, 0.23665937, 0.84603988,
        0.36658924, 0.52999484, 0.77255469, 0.47503961, 0.96432906],
       [0.8297801 , 0.96904642, 0.2352913 , 0.84176215, 0.9327282 ,
        0.90302481, 0.55918363, 0.70254882, 0.79113722, 0.4663697 ],
       [0.08226867, 0.02123295, 0.2566292 , 0.90753836, 0.75136368,
        0.14810476, 0.10719031, 0.94589878, 0.18943642, 0.23430207],
       [0.78243834, 0.56223516, 0.27464376, 0.46161308, 0.41988005,
        0.87734161, 0.10068111, 0.77980709, 0.42706823, 0.64245865],
       [0.12821382, 0.47458584, 0.18567026, 0.38320676, 0.67642554,
        0.75853985, 0.67342783, 0.28062686, 0.00583509, 0.1749425 ],
       [0.1762924 , 0.36096042, 0.51287496, 0.76617998, 0.70095148,
        0.03926494, 0.60546874, 0.19151196, 0.2888023 , 0.07831061],
       [0.2946404 , 0.86591746, 0.2097886